import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test'
import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { resolve, join } from 'node:path'
let app: ElectronApplication
async function launch(scenario: string) {
  const dir = await mkdtemp(join(tmpdir(), 'easyai-e2e-'))
  app = await electron.launch({ args: [resolve('out/main/index.js'), '--demo'], env: { ...process.env, EASYAI_DATA_DIR: dir, EASYAI_SCENARIO: scenario }, timeout: 30000 })
  const page = await app.firstWindow(); await expect(page.getByText('Công cụ sẵn sàng.')).toBeVisible(); return page
}
test.afterEach(async () => { await app?.close() })
test('guided install, approval, verification and explicit user confirmation', async ({}, testInfo) => {
  const page = await launch('success')
  await page.screenshot({ path: testInfo.outputPath('welcome.png'), fullPage: true })
  await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await expect(page.getByRole('button', { name: 'Xác nhận và thực hiện' })).toBeVisible()
  await page.getByRole('button', { name: 'Xác nhận và thực hiện' }).click()
  await expect(page.getByText('Hoàn tất đăng nhập')).toBeVisible()
  await page.getByRole('button', { name: 'Tôi đã dùng được ChatGPT' }).click()
  await expect(page.getByText('Bộ công cụ của bạn đã sẵn sàng')).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('ready.png'), fullPage: true })
})
test('standard user receives BM01 and no install approval', async ({}, testInfo) => {
  const page = await launch('no-admin')
  await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await expect(page.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Xác nhận và thực hiện' })).toHaveCount(0)
  await expect(page.getByText('lordierclaw@gmail.com', { exact: true })).toBeVisible()
  await page.getByText('Xem biểu mẫu BM01 đã điền sẵn').click()
  await expect(page.locator('.support-card pre')).toContainText('không có quyền quản trị')
  await page.getByRole('button', { name: 'Sao chép BM01' }).click()
  await expect(page.getByRole('status')).toContainText('Đã sao chép BM01')
  await page.screenshot({ path: testInfo.outputPath('bm01.png'), fullPage: true })
})
test('network failure gives evidence without claiming proven IP blocking', async () => {
  const page = await launch('network'); await page.getByRole('button', { name: /Khắc phục sự cố/ }).click()
  await expect(page.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  await page.getByText('Xem biểu mẫu BM01 đã điền sẵn').click()
  await expect(page.locator('.support-card pre')).toContainText('CONNECT timed out')
  await expect(page.locator('.support-card pre')).toContainText('Chưa đủ bằng chứng')
})
test('Store failure preserves installed Codex and produces IT handoff', async () => {
  const page = await launch('store'); await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await page.getByRole('button', { name: 'Xác nhận và thực hiện' }).click()
  await expect(page.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  await expect(page.locator('.component').filter({ hasText: 'Codex CLI' })).toContainText('Đã cài đặt')
  await expect(page.getByText('Bộ công cụ của bạn đã sẵn sàng')).toHaveCount(0)
})
test('cancel before approval leaves no installation steps; navigation and log composer remain usable', async () => {
  const page = await launch('success'); await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await page.getByRole('button', { name: 'Để sau' }).click()
  await expect(page.locator('.run-title')).toContainText('Đã hủy')
  await expect(page.locator('.progress-step').filter({ hasText: 'Cài đặt' })).toHaveCount(0)
  await page.getByRole('button', { name: /Kết nối & hỗ trợ/ }).click()
  await expect(page.getByRole('heading', { name: 'Kết nối & hỗ trợ' })).toBeVisible()
  await expect(page.getByText('Sử dụng proxy của Windows')).toBeVisible()
})
test('log attachment, support clipboard and exported diagnostics redact credentials', async ({}, testInfo) => {
  const page = await launch('no-admin')
  const dir = await mkdtemp(join(tmpdir(), 'easyai-dialog-'))
  const log = join(dir, 'sample.log'); const report = join(dir, 'diagnostics.json')
  await writeFile(log, 'Codex lỗi: api_key=sk-example-secret123\nHTTP_PROXY=http://bob:password@proxy:8080')
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }) }, log)
  await page.getByRole('button', { name: 'Đính kèm log' }).click()
  await expect(page.getByRole('textbox', { name: 'Nhập yêu cầu' })).toHaveValue(/\[REDACTED\]/)
  await expect(page.getByRole('textbox', { name: 'Nhập yêu cầu' })).not.toHaveValue(/secret123/)
  await page.getByRole('button', { name: 'Gửi yêu cầu' }).click()
  await expect(page.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }) }, report)
  await page.getByRole('button', { name: 'Xuất chẩn đoán' }).click()
  await expect(page.getByRole('status')).toContainText('Đã xuất')
  const saved = await readFile(report, 'utf8'); expect(saved).not.toContain('secret123'); expect(saved).not.toContain('bob:password')
  expect(JSON.parse(saved).support.code).toBe('IT-001')
  await testInfo.attach('diagnostics', { body: saved, contentType: 'application/json' })
})
test('history persists across app restart and renderer has no Node access', async () => {
  const page = await launch('no-admin'); await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await expect(page.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  expect(await page.evaluate(() => typeof (window as any).require)).toBe('undefined')
  const root = await app.evaluate(({ app }) => app.getPath('userData'))
  await app.close()
  app = await electron.launch({ args: [resolve('out/main/index.js'), '--demo'], env: { ...process.env, EASYAI_DATA_DIR: root, EASYAI_SCENARIO: 'no-admin' } })
  const next = await app.firstWindow(); await next.locator('.history-item').first().click()
  await expect(next.getByText('Cần đội ngũ IT hỗ trợ')).toBeVisible()
  await expect(next.getByRole('button', { name: 'Xác nhận và thực hiện' })).toHaveCount(0)
})
test('stopping an active task keeps the UI usable and requires inspection before continuing', async () => {
  const page = await launch('success'); await page.getByRole('button', { name: /Cài đặt công cụ/ }).click()
  await page.getByRole('button', { name: 'Xác nhận và thực hiện' }).click()
  await page.getByRole('button', { name: 'Dừng tác vụ' }).click()
  await expect(page.locator('.run-title')).toContainText('Bị gián đoạn')
  await expect(page.getByRole('button', { name: 'Kiểm tra lại hiện trạng' })).toBeVisible()
  await expect(page.getByText('Bộ công cụ của bạn đã sẵn sàng')).toHaveCount(0)
  const runs = await page.evaluate(() => window.easy.list()); expect(runs[0].approved).toBe(false)
})
