import { useEffect, useState } from 'react'
import { AssistantRuntimeProvider, useExternalStoreRuntime, ThreadPrimitive, MessagePrimitive } from '@assistant-ui/react'
import Markdown from 'react-markdown'
import { ArrowUp, ArrowUpRight, Check, CheckCheck, CheckCircle2, ChevronRight, Circle, Clock3, Copy, Download, FileText, HelpCircle, Layers3, LoaderCircle, MessageSquare, Monitor, Network, PackageCheck, Paperclip, Plus, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Square, Terminal, Wrench, X, XCircle } from 'lucide-react'
import type { Action, AppInfo, ChatMessage, NetworkCheck, Run, RunStatus } from '../../shared/types'
import { Button } from './components/ui/button'

const labels: Record<RunStatus, string> = { checking: 'Đang kiểm tra', awaiting_approval: 'Chờ xác nhận', running: 'Đang thực hiện', awaiting_input: 'Cần thông tin', awaiting_login: 'Chờ đăng nhập', ready: 'Sẵn sàng', needs_it: 'Cần IT hỗ trợ', interrupted: 'Bị gián đoạn', failed: 'Chưa hoàn tất', cancelled: 'Đã hủy' }
const actions: { id: Action; title: string; description: string; icon: typeof Download; color: string }[] = [
  { id: 'install', title: 'Cài đặt công cụ', description: 'Chuẩn bị mọi thứ để bắt đầu làm việc.', icon: Download, color: 'blue' },
  { id: 'configure', title: 'Cấu hình công cụ', description: 'Kết nối và thiết lập đúng môi trường.', icon: Settings2, color: 'purple' },
  { id: 'repair', title: 'Khắc phục sự cố', description: 'Tìm nguyên nhân và cùng xử lý lỗi.', icon: Wrench, color: 'orange' }
]
function Status({ value }: { value: RunStatus }) { return <span className={`status status-${value}`}><span/>{labels[value]}</span> }
function ChatBubble() {
  return <MessagePrimitive.Root className="message"><div className="message-avatar"><Sparkles size={17}/></div><div className="message-body"><MessagePrimitive.Parts components={{ Text: ({ text }) => <Markdown skipHtml components={{ a: ({ children }) => <span>{children}</span>, img: () => null }}>{text}</Markdown> }}/></div></MessagePrimitive.Root>
}
function Conversation({ messages, running, onSend }: { messages: ChatMessage[]; running: boolean; onSend: (text: string) => Promise<void> }) {
  const runtime = useExternalStoreRuntime({ messages, isRunning: running,
    convertMessage: (m: ChatMessage) => ({ id: m.id, role: m.role, content: [{ type: 'text' as const, text: m.text }] }),
    onNew: async message => { const text = message.content.filter(c => c.type === 'text').map(c => c.type === 'text' ? c.text : '').join('\n'); await onSend(text) } })
  return <AssistantRuntimeProvider runtime={runtime}><ThreadPrimitive.Root><ThreadPrimitive.Viewport className="thread"><ThreadPrimitive.Messages components={{ Message: ChatBubble }}/></ThreadPrimitive.Viewport></ThreadPrimitive.Root></AssistantRuntimeProvider>
}
export function App() {
  const [info, setInfo] = useState<AppInfo>()
  const [runs, setRuns] = useState<Run[]>([])
  const [selected, setSelected] = useState<string>()
  const [page, setPage] = useState<'chat' | 'catalog' | 'connections'>('chat')
  const [text, setText] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [network, setNetwork] = useState<NetworkCheck[]>([])
  const [networkBusy, setNetworkBusy] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const run = runs.find(r => r.id === selected)
  const running = !!run && ['checking', 'running'].includes(run.status)
  const anythingRunning = runs.some(r => ['checking', 'running'].includes(r.status))
  const busy = running || submitting
  useEffect(() => {
    void Promise.all([window.easy.info(), window.easy.list()]).then(([i, r]) => { setInfo(i); setRuns(r) }).catch(e => setError(e.message))
    return window.easy.onEvent(event => {
      if (event.type === 'run') setRuns(previous => [event.run, ...previous.filter(r => r.id !== event.run.id)])
      else setRuns(previous => previous.map(r => r.id === event.runId ? { ...r, messages: r.messages.map(m => m.id === event.messageId ? { ...m, text: event.text } : m) } : r))
    })
  }, [])
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(timer) }, [notice])
  const perform = async (fn: () => Promise<unknown>) => { setError(''); try { await fn() } catch (e) { setError((e as Error).message.replace(/^Error invoking remote method '[^']+': Error: /, '')) } }
  const start = async (action: Action, prompt?: string) => {
    setSubmitting(true)
    await perform(async () => { const r = await window.easy.start(action, prompt); setRuns(previous => previous.some(x => x.id === r.id) ? previous : [r, ...previous]); setSelected(r.id); setPage('chat'); setText('') })
    setSubmitting(false)
  }
  const send = async (value: string) => {
    if (!value.trim()) return
    if (run) await perform(async () => { await window.easy.send(run.id, value.trim()); setText('') })
    else await start(/lỗi|không|sự cố|error/i.test(value) ? 'repair' : /cấu hình|proxy/i.test(value) ? 'configure' : 'install', value.trim())
  }
  const checkConnections = () => { setNetworkBusy(true); void perform(async () => setNetwork(await window.easy.connections())).finally(() => setNetworkBusy(false)) }
  const reset = () => { setSelected(undefined); setPage('chat'); setText(''); setError('') }
  const componentLabel = (status: string) => ({ missing: 'Chưa cài đặt', installed: 'Đã cài đặt', awaiting_login: 'Chờ đăng nhập', ready: 'Sẵn sàng', needs_it: 'Cần IT' }[status] || status)
  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={reset} aria-label="EasyAI trang chủ"><span className="brand-symbol"><Sparkles size={21}/></span><span>easy<span className="brand-ai">ai</span><small>YOUR WORK, SIMPLIFIED</small></span></button>
      <Button variant="secondary" className="new-chat" onClick={reset}><Plus size={17}/> Cuộc trò chuyện mới</Button>
      <nav aria-label="Điều hướng chính">
        <button className={page === 'chat' ? 'nav-item active' : 'nav-item'} onClick={() => setPage('chat')}><MessageSquare size={18}/> Trợ lý của bạn</button>
        <button className={page === 'catalog' ? 'nav-item active' : 'nav-item'} onClick={() => setPage('catalog')}><Layers3 size={18}/> Công cụ được duyệt <span className="nav-count">1</span></button>
        <button className={page === 'connections' ? 'nav-item active' : 'nav-item'} onClick={() => { setPage('connections'); if (!network.length) checkConnections() }}><Network size={18}/> Kết nối & hỗ trợ</button>
      </nav>
      <div className="history-title">GẦN ĐÂY <Clock3 size={13}/></div>
      <div className="history-list">{runs.length ? runs.slice(0, 15).map(r => <button key={r.id} className={`history-item ${r.id === selected ? 'selected' : ''}`} onClick={() => { setSelected(r.id); setPage('chat'); setError('') }}><MessageSquare size={14}/><span>{r.title}<small>{new Date(r.createdAt).toLocaleDateString('vi-VN')} · {labels[r.status]}</small></span></button>) : <p className="empty-history">Các cuộc trò chuyện của bạn sẽ xuất hiện ở đây.</p>}</div>
      <div className="sidebar-bottom"><div className="trusted"><ShieldCheck size={17}/><div>Môi trường doanh nghiệp<small>Làm theo hướng dẫn đã phê duyệt</small></div></div><div className="profile"><span className="profile-avatar">U</span><div>Không gian của bạn<small>EasyAI · v{info?.version || '0.1.0'}</small></div><Monitor size={16}/></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Không gian làm việc <ChevronRight size={14}/><strong>{page === 'catalog' ? 'Công cụ được duyệt' : page === 'connections' ? 'Kết nối & hỗ trợ' : run ? run.title : 'Trợ lý của bạn'}</strong></div><span className="private-label"><ShieldCheck size={14}/> {info?.demo ? 'Chế độ mô phỏng' : info?.sample ? 'Tài liệu mẫu · thao tác thật' : 'Theo quy định doanh nghiệp'}</span></header>
      {info?.demo && <div className="mode-banner"><Monitor size={15}/> Bản trải nghiệm mô phỏng — không cài phần mềm hoặc thay đổi cấu hình máy.</div>}
      {info?.sample && !info.demo && <div className="mode-banner warning"><FileText size={15}/> Đang dùng tài liệu mẫu. Các thao tác được xác nhận sẽ thay đổi máy thật.</div>}
      {error && <div className="error-banner" role="alert"><XCircle size={18}/><span>{error}</span><button aria-label="Đóng lỗi" onClick={() => setError('')}><X size={15}/></button></div>}
      {notice && <div className="toast" role="status"><Check size={16}/>{notice}</div>}
      {page === 'connections' ? <div className="page-content"><div className="eyebrow">MÔI TRƯỜNG LÀM VIỆC</div><h1>Kết nối & hỗ trợ</h1><p className="page-description">Kiểm tra đường kết nối để công cụ hoạt động đúng trong mạng doanh nghiệp.</p><div className="connection-summary"><div className="icon-tile blue"><Network size={23}/></div><div><h3>Sử dụng proxy của Windows</h3><p>EasyAI tự đọc cấu hình hiện có. Bạn không cần nhập thông số kỹ thuật.</p></div><Button variant="secondary" onClick={checkConnections} disabled={networkBusy}><RefreshCw size={15} className={networkBusy ? 'spin' : ''}/>Kiểm tra lại</Button></div><div className="network-list">{networkBusy && !network.length ? <p><LoaderCircle className="spin" size={18}/> Đang kiểm tra kết nối…</p> : network.map(n => <div className="network-row" key={n.name}>{n.reachable ? <CheckCircle2 size={19} className="green-text"/> : <XCircle size={19} className="orange-text"/>}<div><strong>{n.name}</strong><small>{n.url}</small></div><span>{n.reachable ? `Kết nối được${n.status ? ` · HTTP ${n.status}` : ''}` : 'Chưa kết nối được'}</span>{n.error && <small>{n.error}</small>}</div>)}</div><p className="footnote">Kết nối được không đồng nghĩa đã đăng nhập hoặc dịch vụ đã sẵn sàng. HTTP 401/403 vẫn cho thấy máy chủ đã phản hồi.</p><div className="help-card"><HelpCircle size={22}/><div><h3>Cần IT hỗ trợ?</h3><p>Bắt đầu một phiên Khắc phục sự cố để EasyAI thu thập chẩn đoán và tạo nội dung BM01 phù hợp.</p><Button variant="secondary" onClick={() => start('repair')} disabled={anythingRunning}>Khắc phục sự cố <ArrowUpRight size={15}/></Button></div></div></div>
      : page === 'catalog' ? <div className="page-content"><div className="eyebrow">DÀNH CHO CÔNG VIỆC CỦA BẠN</div><h1>Công cụ được duyệt</h1><p className="page-description">Cài đặt và sử dụng công cụ theo hướng dẫn của doanh nghiệp.</p><article className="catalog-card"><div className="catalog-head"><span className="codex-icon"><Terminal size={28}/></span><div><h2>Thiết lập Codex</h2><p>Bộ công cụ hỗ trợ lập trình với AI</p></div><span className="approved"><ShieldCheck size={14}/>Đã có hướng dẫn</span></div><p>EasyAI kiểm tra máy, chuẩn bị các thành phần cần thiết và giúp bạn xử lý sự cố trong quá trình thiết lập.</p><div className="package-tags"><span>Git</span><span>Node.js</span><span>Codex CLI</span><span>ChatGPT Desktop</span></div><div className="catalog-actions"><Button onClick={() => start('install')} disabled={anythingRunning}><Download size={16}/>Bắt đầu cài đặt</Button><Button variant="secondary" onClick={() => start('repair')} disabled={anythingRunning}><Wrench size={16}/>Khắc phục sự cố</Button></div></article><div className="catalog-note"><FileText size={18}/><span>Nội dung do admin publish trên GitHub. Phiên làm việc giữ nguyên phiên bản hướng dẫn đã tải.</span></div></div>
      : <div className={`workspace ${run ? 'has-run' : ''}`}><section className="chat-column">
        {!run ? <div className="welcome"><div className="welcome-mark"><Sparkles size={30}/></div><div className="eyebrow">BỚT THAO TÁC. THÊM HIỆU QUẢ.</div><h1>Công cụ sẵn sàng.<br/><span>Bạn tập trung vào công việc.</span></h1><p className="welcome-description">Tôi giúp bạn cài đặt, cấu hình và xử lý sự cố.<br/>Chọn một nhu cầu bên dưới, phần kỹ thuật để EasyAI lo.</p><div className="action-grid">{actions.map(a => <button className="action-card" key={a.id} onClick={() => start(a.id)} disabled={anythingRunning || submitting}><span className={`icon-tile ${a.color}`}><a.icon size={21}/></span><ArrowUpRight className="card-arrow" size={17}/><h3>{a.title}</h3><p>{a.description}</p></button>)}</div><div className="featured"><span className="mini-codex"><Terminal size={18}/></span><div><strong>Bắt đầu với Codex</strong><span>Git, Node.js, Codex CLI & ChatGPT Desktop</span></div><button onClick={() => setPage('catalog')} aria-label="Xem bộ công cụ Codex"><ChevronRight size={19}/></button></div><div className="welcome-assurance"><ShieldCheck size={15}/>Theo hướng dẫn doanh nghiệp <span>·</span> Bạn xác nhận trước khi thay đổi</div></div>
        : <div className="run-content"><div className="run-title"><div><span className="eyebrow">PHIÊN LÀM VIỆC</span><h2>{run.title}</h2></div><Status value={run.status}/></div><Conversation messages={run.messages} running={running} onSend={send}/>
          {!!run.progress.length && <section className="progress-card" aria-label="Tiến trình"><div className="card-heading"><PackageCheck size={18}/><strong>Tiến trình thực hiện</strong><span>{run.progress.filter(p => p.status === 'done').length}/{run.progress.length}</span></div>{run.progress.map(p => <details className="progress-step" key={p.id}><summary>{p.status === 'running' ? <LoaderCircle size={16} className="spin blue-text"/> : p.status === 'done' ? <CheckCircle2 size={16} className="green-text"/> : <XCircle size={16} className="orange-text"/>}<span>{p.title}</span><ChevronRight size={13}/></summary>{p.detail ? <pre>{p.detail}</pre> : <p>{p.status === 'done' ? 'Kiểm tra đã hoàn tất.' : 'Đang thực hiện…'}</p>}</details>)}</section>}
          {run.status === 'awaiting_approval' && <section className="approval-card" aria-label="Xác nhận phạm vi"><div className="card-heading"><ShieldCheck size={20}/><strong>Sẵn sàng để bắt đầu</strong></div><p>Tôi cần thực hiện những thay đổi sau. Bạn chỉ cần xác nhận một lần cho phạm vi này.</p><ul>{run.approval?.map(a => <li key={a}><Check size={14}/>{a}</li>)}</ul><div className="card-actions"><Button onClick={() => perform(() => window.easy.approve(run.id))}><Check size={16}/>Xác nhận và thực hiện</Button><Button variant="ghost" onClick={() => perform(() => window.easy.cancel(run.id))}>Để sau</Button></div></section>}
          {run.support && <section className="support-card" aria-label="Yêu cầu IT"><div className="card-heading"><HelpCircle size={21}/><strong>Cần đội ngũ IT hỗ trợ</strong></div><p>{run.bundle?.policy.rules.find(r => r.id === run.support?.code)?.message || 'Tôi đã chuẩn bị nội dung chẩn đoán để IT tiếp tục hỗ trợ bạn.'}</p><div className="recipient"><span>GỬI ĐẾN</span><strong>{run.support.recipient}</strong></div><details><summary><FileText size={16}/>Xem biểu mẫu BM01 đã điền sẵn</summary><pre>{run.support.body}</pre></details><div className="card-actions"><Button onClick={() => perform(async () => { await window.easy.copy(`Đến: ${run.support!.recipient}\nTiêu đề: ${run.support!.subject}\n\n${run.support!.body}`); setNotice('Đã sao chép BM01. Bạn kiểm tra và tự gửi email.') })}><Copy size={15}/>Sao chép BM01</Button><Button variant="secondary" onClick={() => perform(() => window.easy.retry(run.id))}><RefreshCw size={15}/>Kiểm tra lại sau hỗ trợ</Button></div><small>EasyAI không tự gửi email. Kiểm tra thông tin trước khi gửi.</small></section>}
          {run.status === 'awaiting_input' && <div className="input-request"><MessageSquare size={18}/>{run.question}</div>}
          {run.status === 'awaiting_login' && <section className="approval-card"><div className="card-heading"><Monitor size={20}/><strong>Hoàn tất đăng nhập</strong></div><p>Đăng nhập tài khoản ChatGPT trong các ứng dụng chính thức. Không gửi mật khẩu hoặc mã xác thực vào hội thoại.</p><div className="card-actions"><Button onClick={() => perform(() => window.easy.open(run.id, 'login'))}>Đăng nhập Codex <ArrowUpRight size={15}/></Button><Button variant="secondary" onClick={() => perform(() => window.easy.open(run.id, 'chatgpt'))}>Mở ChatGPT <ArrowUpRight size={15}/></Button></div><div className="card-actions"><Button variant="secondary" onClick={() => perform(() => window.easy.retry(run.id))}><RefreshCw size={15}/>Kiểm tra sau đăng nhập</Button>{!run.chatgptConfirmed && <Button variant="ghost" onClick={() => perform(() => window.easy.confirmChatGPT(run.id))}><CheckCheck size={16}/>Tôi đã dùng được ChatGPT</Button>}</div></section>}
          {run.status === 'ready' && <section className="success-card"><CheckCircle2 size={28}/><div><h3>Bộ công cụ của bạn đã sẵn sàng</h3><p>{run.demo ? 'Luồng mô phỏng đã hoàn tất.' : 'Các kiểm tra đã đạt. Bạn có thể bắt đầu làm việc.'}</p><Button onClick={() => perform(() => window.easy.open(run.id, 'codex'))}>Mở Codex <ArrowUpRight size={15}/></Button></div></section>}
          {run.error && <div className="run-error" role="status"><XCircle size={18}/><p>{run.error}</p></div>}
          {['failed', 'interrupted', 'cancelled'].includes(run.status) && <Button variant="secondary" onClick={() => perform(() => window.easy.retry(run.id))}><RefreshCw size={15}/>Kiểm tra lại hiện trạng</Button>}
        </div>}
        <div className="composer-wrap"><form className={`composer ${busy ? 'composer-busy' : ''}`} onSubmit={event => { event.preventDefault(); void send(text) }}><textarea aria-label="Nhập yêu cầu" placeholder={run ? 'Mô tả thêm vấn đề hoặc trả lời EasyAI…' : 'Bạn cần hỗ trợ gì? Ví dụ: Tôi muốn cài Codex…'} value={text} onChange={e => setText(e.target.value)} disabled={busy} rows={2} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); if (!busy) void send(text) } }}/><div className="composer-toolbar"><button type="button" aria-label="Đính kèm log" disabled={busy} onClick={() => perform(async () => { const log = await window.easy.attach(); if (log) setText(t => (t + '\nLog đính kèm:\n' + log).slice(0, 30000)) })}><Paperclip size={18}/></button><span><ShieldCheck size={13}/>Hỗ trợ theo hướng dẫn đã duyệt</span>{running ? <Button type="button" variant="secondary" size="icon" aria-label="Dừng tác vụ" onClick={() => perform(() => window.easy.cancel(run!.id))}><Square size={15}/></Button> : <Button size="icon" type="submit" aria-label="Gửi yêu cầu" disabled={!text.trim() || submitting}><ArrowUp size={19}/></Button>}</div></form><p className="composer-note">Bạn luôn có thể xem chi tiết. EasyAI chỉ thay đổi máy trong phạm vi được xác nhận.</p></div>
      </section>{run && <aside className="context-panel"><div className="context-title"><span className="mini-codex"><Terminal size={17}/></span><div><strong>Bộ công cụ Codex</strong><small>Trạng thái kiểm chứng</small></div></div><div className="component-list">{run.inspection?.components.map(c => <div className="component" key={c.id}><div>{c.status === 'ready' ? <CheckCircle2 size={17} className="green-text"/> : <Circle size={17}/>}<strong>{c.name}</strong></div><span className={c.status === 'ready' ? 'green-text' : ''}>{componentLabel(c.status)}</span>{c.version && <small>{c.version}</small>}{c.detail && <details><summary>Chi tiết</summary><p>{c.detail}</p></details>}</div>) || <p className="muted">Đang đọc hướng dẫn…</p>}</div>{run.inspection && <div className="context-section"><span className="eyebrow">MÔI TRƯỜNG</span><p><Monitor size={15}/>{run.inspection.windows}</p><p><ShieldCheck size={15}/>{run.inspection.admin ? 'Có thể yêu cầu UAC' : 'Tài khoản tiêu chuẩn'}</p><p><Network size={15}/>{run.inspection.proxy.enabled ? 'Proxy Windows đang bật' : 'Windows không bật proxy cố định'}</p></div>}{run.bundle && <div className="context-section"><span className="eyebrow">HƯỚNG DẪN ĐANG DÙNG</span><p><FileText size={15}/>{run.bundle.source === 'sample' ? 'Tài liệu mẫu' : run.bundle.source === 'cache' ? 'Bản lưu hợp lệ gần nhất' : 'Đã tải từ GitHub'}</p><code>{run.bundle.revision.slice(0, 12)}</code><small>Phiên này giữ nguyên phiên bản tài liệu.</small></div>}<Button variant="secondary" className="export-button" onClick={() => perform(async () => { if (await window.easy.export(run.id)) setNotice('Đã xuất báo cáo chẩn đoán.') })}><Download size={15}/>Xuất chẩn đoán</Button></aside>}</div>}
    </main>
  </div>
}
