import { useEffect, useState } from 'react'
import { AssistantRuntimeProvider, useExternalStoreRuntime, ThreadPrimitive, MessagePrimitive } from '@assistant-ui/react'
import Markdown from 'react-markdown'
import { Activity, ArrowUp, Bell, BookOpen, Check, CheckCircle2, ChevronRight, CircleHelp, Copy, Download, FileText, History, LoaderCircle, MessageSquare, Network, Paperclip, Plus, ShieldCheck, Sparkles, Square, Terminal, Wrench, XCircle } from 'lucide-react'
import type { GuideAction, GuideInfo, GuideRun, GuideStatus, GuideSupport, TraceEvent } from '../../shared/guide'
import { Button } from './components/ui/button'
import './guide.css'
const labels: Record<GuideStatus, string> = { reading: 'Đang đọc guide', running: 'Đang thực hiện', awaiting_approval: 'Chờ xác nhận', awaiting_input: 'Cần phản hồi', awaiting_login: 'Chờ bạn thao tác', needs_it: 'Cần IT hỗ trợ', ready: 'Sẵn sàng', failed: 'Chưa hoàn tất', interrupted: 'Bị gián đoạn', cancelled: 'Đã hủy' }
const actions: { action: GuideAction; title: string; detail: string; icon: typeof Download; color: string }[] = [
  { action: 'install', title: 'Cài đặt công cụ', detail: 'Chuẩn bị môi trường làm việc', icon: Download, color: 'indigo' },
  { action: 'configure', title: 'Cấu hình công cụ', detail: 'Thiết lập theo hướng dẫn', icon: Wrench, color: 'green' },
  { action: 'repair', title: 'Khắc phục sự cố', detail: 'Tìm nguyên nhân từ bằng chứng', icon: CircleHelp, color: 'orange' }
]
function Body({ text }: { text: string }) { return <Markdown skipHtml components={{ a: ({ children }) => <span>{children}</span>, img: () => null }}>{text}</Markdown> }
function Message() { return <MessagePrimitive.Root className="g-message"><span className="g-avatar"><Sparkles size={17}/></span><div><MessagePrimitive.Parts components={{ Text: ({ text }) => <Body text={text}/> }}/></div></MessagePrimitive.Root> }
function Conversation({ run, send }: { run: GuideRun; send(text: string): Promise<void> }) {
  const runtime = useExternalStoreRuntime({ messages: run.messages, isRunning: ['reading', 'running'].includes(run.status), convertMessage: m => ({ id: m.id, role: m.role, content: [{ type: 'text' as const, text: m.text }] }), onNew: async m => send(m.content.flatMap(c => c.type === 'text' ? [c.text] : []).join('\n')) })
  return <AssistantRuntimeProvider runtime={runtime}><ThreadPrimitive.Root><ThreadPrimitive.Viewport><ThreadPrimitive.Messages components={{ Message }}/></ThreadPrimitive.Viewport></ThreadPrimitive.Root></AssistantRuntimeProvider>
}
function Support({ run, perform }: { run: GuideRun; perform(fn: () => Promise<unknown>): Promise<void> }) {
  const [draft, setDraft] = useState<GuideSupport>(run.support!)
  useEffect(() => setDraft(run.support!), [run.support])
  const save = () => window.guide.saveSupport(run.id, draft)
  return <section className="g-support"><div className="g-section-title"><CircleHelp/><h3>Chuẩn bị yêu cầu IT</h3></div><p>{draft.reason}</p><ol>{draft.instructions.map((s, i) => <li key={i}>{s}</li>)}</ol>
    <label>Người nhận<div className="g-copy-field"><input aria-label="Người nhận" value={draft.recipient} onChange={e => setDraft({ ...draft, recipient: e.target.value })}/><Button variant="secondary" aria-label="Sao chép người nhận" onClick={() => perform(() => window.guide.copy(draft.recipient))}><Copy size={15}/></Button></div></label>
    <label>Tiêu đề<div className="g-copy-field"><input aria-label="Tiêu đề email" value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })}/><Button variant="secondary" aria-label="Sao chép tiêu đề" onClick={() => perform(() => window.guide.copy(draft.subject))}><Copy size={15}/></Button></div></label>
    <label>Nội dung email<textarea aria-label="Nội dung email" rows={9} value={draft.body} onChange={e => setDraft({ ...draft, body: e.target.value })}/></label>
    <div className="g-buttons"><Button onClick={() => perform(async () => { await save(); await window.guide.copy(draft.body) })}><Copy size={15}/>Sao chép nội dung</Button><Button variant="secondary" onClick={() => perform(async () => { await save(); await window.guide.exportSupport(run.id) })}><Download size={15}/>Lưu Markdown</Button><Button variant="secondary" onClick={() => perform(() => window.guide.retry(run.id))}>Kiểm tra lại sau hỗ trợ</Button></div>
    <details><summary>Bằng chứng kỹ thuật riêng</summary><pre>{draft.evidence}</pre></details><small>Kiểm tra nội dung rồi gửi bằng email của bạn. EasyAI không tự gửi email.</small>
  </section>
}
export function GuideApp() {
  const [runs, setRuns] = useState<GuideRun[]>([]); const [catalog, setCatalog] = useState<GuideInfo[]>([]); const [guideId, setGuide] = useState(''); const [selected, setSelected] = useState<string>(); const [page, setPage] = useState<'chat' | 'catalog' | 'connections' | 'trace'>('chat')
  const [info, setInfo] = useState<{ version: string; demo: boolean; sample: boolean }>(); const [text, setText] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [submitting, setSubmitting] = useState(false); const [clock, setClock] = useState(Date.now()); const [trace, setTrace] = useState<TraceEvent[]>([]); const [connections, setConnections] = useState<{ name: string; reachable: boolean; detail: string }[]>([])
  const run = runs.find(r => r.id === selected); const running = !!run && ['reading', 'running'].includes(run.status); const active = runs.some(r => ['reading', 'running'].includes(r.status)); const chosen = catalog.find(g => g.id === guideId)
  useEffect(() => {
    void window.guide.info().then(setInfo)
    void window.guide.list().then(setRuns).catch(e => setError(e.message))
    void window.guide.catalog().then(c => { setCatalog(c); setGuide(c[0]?.id || '') }).catch(e => setError(e.message))
    const off = window.guide.onEvent(event => {
      if (event.type === 'run') setRuns(previous => [event.run, ...previous.filter(r => r.id !== event.run.id)])
      else if (event.type === 'select') { setSelected(event.runId); setPage('chat') }
      else setRuns(previous => previous.map(r => r.id === event.runId ? { ...r, messages: r.messages.map(m => m.id === event.messageId ? { ...m, text: event.text } : m) } : r))
    })
    const timer = setInterval(() => setClock(Date.now()), 1000)
    return () => { off(); clearInterval(timer) }
  }, [])
  useEffect(() => { if (page === 'trace' && run) void window.guide.trace(run.id).then(setTrace).catch(e => setError(e.message)) }, [page, run?.id, run?.status])
  const perform = async (fn: () => Promise<unknown>) => { setError(''); try { await fn() } catch (e) { setError((e as Error).message.replace(/^Error invoking remote method '[^']+': Error: /, '')) } }
  const start = async (action: GuideAction, message?: string) => {
    setSubmitting(true); await perform(async () => { const r = await window.guide.start(guideId, action, message); setRuns(p => [r, ...p.filter(x => x.id !== r.id)]); setSelected(r.id); setPage('chat'); setText('') }); setSubmitting(false)
  }
  const send = async (value: string) => { if (!value.trim()) return; if (run) await perform(async () => { await window.guide.send(run.id, value); setText('') }); else await start('install', value) }
  const busyActivity = run?.activities.slice().reverse().find(a => a.state === 'running')
  return <div className="g-app"><aside className="g-sidebar"><div className="g-brand"><span><Sparkles size={24}/></span><strong>easy<span>ai</span></strong></div><p className="g-tagline">CÔNG VIỆC, ĐƠN GIẢN HƠN.</p><button className="g-new" onClick={() => { setSelected(undefined); setPage('chat') }}><Plus size={18}/>Phiên làm việc mới</button>
    <nav><button className={page === 'chat' ? 'selected' : ''} onClick={() => setPage('chat')}><MessageSquare size={18}/>Trợ lý của bạn</button><button className={page === 'catalog' ? 'selected' : ''} onClick={() => setPage('catalog')}><BookOpen size={18}/>Hướng dẫn công cụ<span>{catalog.length}</span></button><button className={page === 'connections' ? 'selected' : ''} onClick={() => { setPage('connections'); void perform(async () => setConnections(await window.guide.connections())) }}><Network size={18}/>Kết nối & hỗ trợ</button></nav>
    <div className="g-history-title"><History size={14}/>GẦN ĐÂY</div><div className="g-history">{runs.map(r => <button key={r.id} className={selected === r.id ? 'selected' : ''} onClick={() => { setSelected(r.id); setPage('chat') }}><FileText size={15}/><span>{r.title}<small>{labels[r.status]}{r.legacy ? ' · phiên cũ' : ''}</small></span></button>)}</div><div className="g-sidebar-footer"><ShieldCheck size={17}/><span>Theo guide được doanh nghiệp publish<small>EasyAI {info?.version}</small></span></div></aside>
    <main className="g-main"><header><span>Không gian làm việc <ChevronRight size={14}/> {page === 'trace' ? 'Trace phiên AI' : 'Trợ lý của bạn'}</span><span className="g-mode"><span className="g-dot"/>{info?.demo ? 'Mô phỏng' : info?.sample ? 'Guide mẫu · thao tác thật' : 'Môi trường doanh nghiệp'}</span></header>
      {info?.demo && <div className="g-banner">Chế độ mô phỏng — tool không cài phần mềm hoặc thay đổi máy thật.</div>}{info?.sample && !info.demo && <div className="g-banner warn">Đang dùng guide mẫu. Thao tác đã duyệt có thể thay đổi máy.</div>}
      {error && <div className="g-error" role="alert"><XCircle size={18}/>{error}<button aria-label="Đóng lỗi" onClick={() => setError('')}>×</button></div>}{notice && <div className="g-notice" role="status" onClick={() => setNotice('')}>{notice}</div>}
      <div className="g-scroll">{page === 'catalog' ? <><div className="g-page-heading"><BookOpen/><h1>Hướng dẫn được publish</h1></div><p>Mỗi công cụ bắt đầu từ GUIDE.md. AI đọc hướng dẫn trước khi đề xuất thao tác.</p><div className="g-catalog">{catalog.map(g => <button key={g.id} onClick={() => { setGuide(g.id); setSelected(undefined); setPage('chat') }}><BookOpen/><h3>{g.name}</h3><p>{g.description}</p><span>Chọn guide <ChevronRight size={15}/></span></button>)}</div></>
      : page === 'connections' ? <><h1>Kết nối & hỗ trợ</h1><p>EasyAI đọc proxy cố định từ Windows; cấu hình AI được quản lý nội bộ.</p><Button onClick={() => perform(async () => setConnections(await window.guide.connections()))}>Kiểm tra lại kết nối</Button>{connections.map(c => <div className="g-connection" key={c.name}>{c.reachable ? <CheckCircle2/> : <XCircle/>}<strong>{c.name}</strong><span>{c.detail}</span></div>)}<p><Bell size={16}/>Windows sẽ thông báo khi cần bạn phản hồi hoặc khi phiên hoàn tất. Focus Assist có thể ẩn toast.</p></>
      : page === 'trace' && run ? <><div className="g-section-title"><Terminal/><h1>Trace · {run.title}</h1><Button variant="secondary" onClick={() => perform(async () => setTrace(await window.guide.trace(run.id)))}>Làm mới</Button><Button onClick={() => perform(() => window.guide.export(run.id))}>Xuất chẩn đoán</Button></div><p>Input/output và sự kiện Pi đã che secret · lưu tối đa 14 ngày / 200 MB.</p>{trace.map(e => <details className="g-trace" key={e.sequence}><summary><code>{e.kind}</code><span>{e.summary}</span><time>{new Date(e.at).toLocaleTimeString()}</time></summary><p>Turn: {e.turnId || '—'} · Request: {e.requestId || '—'} · Tool: {e.toolCallId || '—'}</p><pre>{JSON.stringify(e.payload, null, 2)}</pre></details>)}</>
      : !run ? <div className="g-welcome"><span className="g-welcome-icon"><Sparkles size={34}/></span><p className="g-eyebrow">BẮT ĐẦU TỪ HƯỚNG DẪN. HOÀN THÀNH BẰNG KIỂM CHỨNG.</p><h1>Công cụ sẵn sàng.<br/><span>Bạn tập trung vào công việc.</span></h1><p>Chọn công cụ và nhu cầu. EasyAI sẽ đọc guide, kiểm tra và cùng bạn thực hiện.</p><label className="g-guide-select">Hướng dẫn<select aria-label="Chọn hướng dẫn" value={guideId} onChange={e => setGuide(e.target.value)}>{catalog.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><div className="g-actions">{actions.map(a => <button key={a.action} className={a.color} disabled={active || submitting || !chosen?.actions.includes(a.action)} onClick={() => start(a.action)}><a.icon size={25}/><strong>{a.title}</strong><span>{a.detail}</span><ChevronRight size={18}/></button>)}</div><div className="g-guide-summary"><BookOpen size={23}/><div><strong>{chosen?.name || 'Chưa tải được danh mục'}</strong><p>{chosen?.description || 'Kiểm tra kết nối và nguồn hướng dẫn.'}</p></div></div></div>
      : <div className="g-session"><div className="g-session-heading"><div><p className="g-eyebrow">PHIÊN LÀM VIỆC</p><h1>{run.title}</h1></div><span className={`g-status ${run.status}`}>{['reading', 'running'].includes(run.status) ? <LoaderCircle className="g-spin" size={15}/> : <Activity size={15}/>} {labels[run.status]}</span></div>
        <div className="g-session-meta"><BookOpen size={14}/>{run.bundle?.source || (run.legacy ? 'Lịch sử phiên cũ' : 'Đang tải guide')} · {run.bundle?.revision.slice(0, 12)}<button onClick={() => setPage('trace')}><Terminal size={14}/>Trace</button><button onClick={() => perform(() => window.guide.export(run.id))}><Download size={14}/>Chẩn đoán</button></div>
        {run.legacy && <div className="g-banner warn">Phiên cũ được giữ để xem/xuất. <Button variant="secondary" onClick={() => perform(async () => { const r = await window.guide.start(run.guideId, run.action, 'Tiếp tục công việc từ phiên cũ, kiểm tra lại hiện trạng.', run.id); setSelected(r.id) })}>Tiếp tục bằng phiên mới</Button></div>}
        <Conversation run={run} send={send}/>
        {running && <div className="g-live" role="status"><LoaderCircle className="g-spin" size={18}/><span>{busyActivity ? busyActivity.title : 'AI đang đọc kết quả và chuẩn bị bước tiếp theo…'}</span>{busyActivity && <time>{Math.max(0, Math.round((clock - Date.parse(busyActivity.startedAt)) / 1000))}s</time>}</div>}
        {!!run.activities.length && <section className="g-timeline"><div className="g-section-title"><Activity size={18}/><h3>Hoạt động thực tế</h3></div>{run.activities.map(a => <details key={a.id} className={a.state}><summary>{a.state === 'running' ? <LoaderCircle size={16} className="g-spin"/> : a.state === 'done' ? <CheckCircle2 size={16}/> : <XCircle size={16}/>}<span>{a.title}</span><small>{a.endedAt ? `${Math.max(0, Math.round((Date.parse(a.endedAt) - Date.parse(a.startedAt)) / 1000))}s` : 'Đang chạy'}</small></summary><pre>{a.detail || 'Đang chờ kết quả từ tool…'}</pre></details>)}</section>}
        {run.status === 'awaiting_approval' && run.hookApproval && <section className="g-approval"><h3>Cần xác nhận bổ sung</h3><p>{run.hookApproval.reason}</p><details><summary>Yêu cầu cụ thể</summary><pre>{JSON.stringify(run.hookApproval.payload, null, 2)}</pre></details><Button onClick={() => perform(() => window.guide.approve(run.id))}>Xác nhận yêu cầu này</Button></section>}
        {run.status === 'awaiting_approval' && !run.hookApproval && run.plan && <section className="g-approval"><h3>Phạm vi cần bạn xác nhận</h3><p>{run.plan.summary}</p><ul>{run.plan.steps.map(s => <li key={s.id}>{s.title}<details><summary>Xem thao tác cụ thể</summary><pre>{JSON.stringify(s.change, null, 2)}</pre></details></li>)}</ul><p>Kiểm chứng: {run.plan.checks.map(c => c.title).join('; ')}.</p><div className="g-buttons"><Button onClick={() => perform(() => window.guide.approve(run.id))}><Check size={16}/>Xác nhận và thực hiện</Button><Button variant="secondary" onClick={() => perform(() => window.guide.cancel(run.id))}>Để sau</Button></div></section>}
        {run.question && <div className="g-question"><CircleHelp size={20}/><strong>{run.question}</strong></div>}
        {!!run.checks.length && <section className="g-checks"><h3>Kết quả kiểm chứng</h3>{run.checks.map(c => <div key={c.id}>{c.passed ? <CheckCircle2 className="g-green" size={18}/> : <CircleHelp className="g-orange" size={18}/>}<span>{c.title}<small>{c.passed ? 'Đạt' : c.detail}</small></span>{!c.passed && run.status === 'awaiting_login' && run.plan?.checks.find(x => x.id === c.id)?.userConfirmation && <Button variant="secondary" onClick={() => perform(() => window.guide.confirm(run.id, c.id))}>Tôi đã hoàn tất bước này</Button>}</div>)}</section>}
        {run.support && <Support run={run} perform={async fn => { await perform(async () => { await fn(); setNotice('Đã xử lý yêu cầu. Nội dung hỗ trợ vẫn có thể chỉnh sửa trước khi gửi.') }) }}/>} {run.status === 'ready' && <div className="g-success"><CheckCircle2/><div><h3>Công việc đã sẵn sàng</h3><p>Các kiểm chứng bắt buộc đã đạt.</p></div></div>}
        {run.error && <div className="g-error" role="alert">{run.error}</div>}{run.traceWarning && <div className="g-banner warn">{run.traceWarning}</div>}
        {['failed', 'interrupted', 'cancelled'].includes(run.status) && !run.legacy && <Button variant="secondary" onClick={() => perform(() => window.guide.retry(run.id))}>Kiểm tra lại hiện trạng</Button>}
      </div>}</div>
      {page === 'chat' && !run?.legacy && <div className="g-composer-wrap"><form className="g-composer" onSubmit={e => { e.preventDefault(); void send(text) }}><textarea aria-label="Nhập yêu cầu" placeholder={run ? 'Trả lời hoặc bổ sung thông tin cho EasyAI…' : 'Bạn cần hỗ trợ gì?'} value={text} onChange={e => setText(e.target.value)} disabled={running || submitting} rows={2}/><div><button type="button" aria-label="Đính kèm log" disabled={running} onClick={() => perform(async () => { const attached = await window.guide.attach(); if (attached) setText(t => (t + '\n' + attached).slice(0, 100000)) })}><Paperclip size={18}/></button><small><ShieldCheck size={13}/>Thay đổi máy sau khi bạn xác nhận</small>{running ? <Button variant="secondary" size="icon" type="button" aria-label="Dừng tác vụ" onClick={() => perform(() => window.guide.cancel(run!.id))}><Square size={17}/></Button> : <Button size="icon" aria-label="Gửi yêu cầu" disabled={!text.trim() || submitting || (!run && !guideId)}><ArrowUp size={19}/></Button>}</div></form><p>Tiến trình lấy từ kết quả tool thực tế. Chi tiết kỹ thuật luôn có thể mở xem.</p></div>}
    </main></div>
}
